### PR TITLE
Add flat GeoJSON properties management due to issue #3 from @tyrasd

### PR DESCRIPTION
**Pull request by ThomasG77**
The modification have been done in `cli.js`, `index.js` and also in the documentation `README.md`

As I used the ternary operator in the `index.js` file, you may want to use a variable if you feel it's too lengthy.

Thanks for your feedback and also this library.

### CODE REVIEW

**Comment by tyrasd** [comment]
:+1: 

only a minor note: the command line syntax `query-overpass --flat-properties true` looks a bit unusual to me. normally, double-dashed parameters are separated by their value with an equal sign (e.g. `--foo-bar=asdfasd`) and typically boolean flags such as this one don't use a value at all (instead, there often is a `--no-xxx` option to explicitly indicate the negation). I think that's also how `minimist` interprets these parameters, so the `true` in the readme example will likely be ignored anyway.

**Comment by ThomasG77** [comment]
I'm also unhappy with the option to set explicitly --flat-properties to `true` whereas --flat-properties should be enough. Unfortunately, I didn't find in `minimist` an option to get the correct behaviour.

`query-overpass --flat-properties query_01.ql` does not work because `minimist` is expecting a key/value input. Hence, `query-overpass --flat-properties query_01.ql query_01.ql` an uglier solution would work.

FIY using `--flat-properties=true` does work too. I just mimicked the documentation for `--overpass-url http://my.overpass-provider.org/`

**Comment by ThomasG77** [comment]
I've done change so `--flat-properties` is now enough.
@perliedman , at the moment, I have now two commits in this PR but I can make another PR to keep history clean if you prefer.

**Comment by perliedman** [comment]
Nice work, @ThomasG77!

In a small project like this, I tend to not worry too much about keeping history clean, so this is fine.

Thanks!

**Comment by tyrasd** [comment]
Perfect. @perliedman: Do you plan to release this as `v1.0.1` on npm?

**Comment by perliedman** [comment]
Again, sorry for taking so long to respond to things here.

I published version 1.1.0 just now, which contains this new feature. Since it's a new feature, I bumped the minor version, not the patch. I guess this shouldn't make difference for you.

**Comment by tyrasd** [comment]
No, that's perfectly fine. Thanks! :+1:

**Pull request merged**
